swagger: '2.0'
host: eurofurencewebapi.azurewebsites.net
consumes:
  - application/json
produces:
  - application/json
info:
  version: 0.0.7
  title: Eurofurence Mobile Apps Web API
  contact:
    name: Luchs
    url: https://forum.eurofurence.org
    
  
paths:
  /Endpoint:
    get:
      description: Gets metadata information about the API Endpoint.
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Endpoint'
  /EventEntry:
    get:
      description: Retrieves a list of all events in the event schedule.
      parameters:
        - $ref: "#/parameters/deltaSinceDateTimeUtc"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/EventEntry'

  /EventConferenceTrack:
    get:
      description: Retrieves a list of all event conference tracks.
      parameters:
        - $ref: "#/parameters/deltaSinceDateTimeUtc"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/EventConferenceTrack'              
              
  /EventConferenceDay:
    get:
      description: Retrieves a list of all event conference days.
      parameters:
        - $ref: "#/parameters/deltaSinceDateTimeUtc"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/EventConferenceDay'                     

  /EventConferenceRoom:
    get:
      description: Retrieves a list of all conference rooms.
      parameters:
        - $ref: "#/parameters/deltaSinceDateTimeUtc"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/EventConferenceRoom'   

  /InfoGroup:
    get:
      description: tbd
      parameters:
        - $ref: "#/parameters/deltaSinceDateTimeUtc"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/InfoGroup'   
              
  /Info:
    get:
      description: tbd
      parameters:
        - $ref: "#/parameters/deltaSinceDateTimeUtc"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Info'   
              
  /Image:
    get:
      description: tbd
      parameters:
        - $ref: "#/parameters/deltaSinceDateTimeUtc"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Image'   
              
  /Announcement:
    get:
      description: tbd
      parameters:
        - $ref: "#/parameters/deltaSinceDateTimeUtc"
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Announcement'                  

parameters:
  deltaSinceDateTimeUtc:
    name: since
    in: query
    description: 'Delta reference, date time in **ISO 8610**. If set, only items 
      with a *LastChangeDateTimeUtc* >= the specified value will be returned.
      If not set, API will return the current set of records without
      deleted items. If set, items deleted since the delta specified will be
      returned with an *IsDeleted* flag set.'
    required: false
    type: string
    format: date-time  
      
definitions:
  EntityBase:
    type: object
    properties:
      Id:
        type: string
        format: uuid
        description: Universally Unique Identifier (16bytes / 36char string),
          e.g 550e8400-e29b-11d4-a716-446655440000
      LastChangeDateTimeUtc:
        type: string
        format: date-time
        description: Date & Time (UTC) in **ISO 8601** format of when the entity was
          last changed. (Will also be updated upon deletion)
      IsDeleted:
        type: number
        minimum: 0
        maximum: 1
        description: Numeric flag that, if set to "1", indicates that the
          record has been deleted sine the delta reference specified, and
          should be removed from the local data store after retrieval.
    required:
      - Id
      - LastChangeDateTimeUtc
      - IsDeleted
    example:
      Id: 550e8400-e29b-11d4-a716-446655440000
      LastChangeDateTimeUtc: 2016-01-26T22:24:46Z
      IsDeleted: 0
      
  EventEntry:
    type: object
    allOf: 
    - $ref: '#/definitions/EntityBase'
    - type: object
      properties:
        SourceEventId:
          type: number
        ImageId:
          type: string
          format: uuid
        Slug:
          type: string
        Title:
          type: string
        ConferenceTrackId:
          type: string
          format: uuid
        ConferenceDayId:
          type: string
          format: uuid
        ConferenceRoomId:
          type: string
          format: uuid
        Abstract:
          type: string
        Description:
          type: string
        StartTime:
          type: string
        EndTime:
          type: string
        Duration:
          type: string
        PanelHosts:
          type: string
      required:
        - SourceEventId
        - Slug
        - Title
        - ConferenceTrackId
        - Abstract
        - Description
        - ConferenceDayId
        - StartTime
        - EndTime
        - Duration
        - ConferenceRoomId
        - PanelHosts
    example:
      Id: 550e8400-e29b-11d4-a716-446655440000
      LastChangeDateTimeUtc: 2016-01-26T22:24:46Z
      IsDeleted: 0
      SourceEventId: 123
      Slug: artist_lounge_tue
      Title: Artist's Lounge - Let's be creative together!
      ConferenceTrackId: e6ea7350-c2c9-11e5-855c-00155d17ae4a
      ConferenceDayId: 55c7f0dd-c46f-11e5-af20-00155d17ae4a
      ConferenceRoomId: 15c7f0dd-c46f-11e5-af20-00155d17ae4b
      Abstract: Do you like spending your evening around other artists, drawing and chatting about techniques? Then this social event, taking place every evening, is the right place for you to be creative!
      Description: Do you like spending your evening around other artists, drawing and chatting about techniques? Then this social event, taking place every evening, is the right place for you to be creative!
      StartTime: '14:00:00'
      EndTime: '02:00:00'
      Duration: '12:00:00'
      PanelHosts: Akulatraxas
          
  EventConferenceDay:
    type: object
    allOf: 
    - $ref: '#/definitions/EntityBase'
    - type: object    
      properties:
        Name:
          type: string
          description: Name of the conference day, e,g, "Sat - Con Day 4".          
        Date:
          type: string
          format: date (YYYY-MM-DD)
          description: Conference day in date format (YYYY-MM-DD) 
      required:
      - Name
      - Date
    example:
      Id: 550e8400-e29b-11d4-a716-446655440000
      LastChangeDateTimeUtc: 2016-01-26T22:24:46Z
      IsDeleted: 0
      Name: Tue - Early Arrival
      Date: '2015-08-18'
          
  EventConferenceTrack:
    type: object
    allOf: 
    - $ref: '#/definitions/EntityBase'
    - type: object    
      properties:
        Name:
          type: string
          description: Name of the conference track.
      required:
      - Name
    example:
      Id: 550e8400-e29b-11d4-a716-446655440000
      LastChangeDateTimeUtc: 2016-01-26T22:24:46Z
      IsDeleted: 0
      Name: Stage

  EventConferenceRoom:
    type: object
    allOf: 
    - $ref: '#/definitions/EntityBase'
    - type: object    
      properties:
        Name:
          type: string
          description: Name of the conference room.
        ImageEntryId:
          type: string
          description: Id of the (map) image that shows the room
        ImageRoomPositionPoint:
          type: string
          format: X,Y
          description: Percentual coordinates on the original image indicating
            the entrance of the room.
      required:
      - Name
    example:
      Id: 550e8400-e29b-11d4-a716-446655440000
      LastChangeDateTimeUtc: 2016-01-26T22:24:46Z
      IsDeleted: 0
      Name: Conference Room 2 - Estrel Hall A      

  Endpoint:
    type: object
    properties:
      CurrentDateTimeUtc:
        type: string
        format: date-time
      Configuration:
        type: array
        items:
          $ref: '#/definitions/EndpointConfiguration'
      Entities:
        type: array
        items:
          $ref: '#/definitions/EndpointEntity'
          
  EndpointConfiguration:
    type: object
    properties:
      Id:
        type: string
        format: uuid
      ResourceKey:
        type: string
      Value:
        type: string
        
  EndpointEntity:
    type: object
    properties:
      Id:
        type: string
        format: uuid
      Name:
        type: string
      TableName:
        type: string
      LastChangeDateTimeUtc:
        type: string
        format: date-time
      Count:
        type: number
        description: Number of records (including deleted ones) in the table.

  InfoGroup:
    type: object
    allOf: 
    - $ref: '#/definitions/EntityBase'
    - type: object
      properties:
        Name:
          type: string
          description: Name of the information group
        Description:
          type: string
          description: Shhort description of the information group
        ImageId:
          type: string
          format: uuid          
        Position:
          type: integer
          description: Numeric order/position of the element (lower number =
            display first)
    example:
      Id: 12345678-e29b-11d4-a716-446655440000
      LastChangeDateTimeUtc: 2016-01-26T22:24:46Z
      IsDeleted: 0
      Name: Fursuit Information
      Description: Various helpful information helpful to fursuiters.
      Position: 4
  
  Info:
    type: object
    allOf: 
    - $ref: '#/definitions/EntityBase'
    - type: object
      properties:
        InfoGroupId:
          type: string
          format: uuid
          description: Id of the InfoGroup this record belongs to.
        ImageId:
          type: string
          format: uuid
        Title:
          type: string
          description: Title of the message blob.
        Text:
          type: string
          description: Content of the message blob, may contain markup (tbd).
        Position:
          type: integer
          description: Numeric order/position of the element (lower number =
            display first)          
    example:
      Id: 34567890-e29b-11d4-a716-446655440000
      LastChangeDateTimeUtc: 2016-01-26T22:24:46Z
      IsDeleted: 0
      InfoGroupId: 12345678-e29b-11d4-a716-446655440000
      Title: Fursuit Parade
      Text: Don't miss out when the entire furry tribe gathers for their annual
        march through the overgrown ruins of ancient societies , and assembles
        near the old canal to capture the moment in full color pictures. 
        The Eurofurence Parade is traditionally an outdoor event, 
        if the weather permits.
      Position: 1

  Image:
    type: object
    allOf: 
    - $ref: '#/definitions/EntityBase'
    - type: object
      properties:
        Url:
          type: string
        Title:
          type: string
        Width:
          type: integer
        Height:
          type: integer    
        FileSizeInBytes:
          type: integer
        MimeType:
          type: string

  Announcement:
    type: object
    allOf:
    - $ref: '#/definitions/EntityBase'
    - type: object
      properties:
        ValidFromDateTimeUtc:
          type: string
          format: date-time
        ValidUntilDateTimeUtc:
          type: string
          format: date-time
        Area:
          type: string
        Author:
          type: string
        Title:
          type: string
        Content:
          type: string
      required:
      - ValidFromDateTimeUtc
      - ValidUntilDateTimeUtc
      - Area
      - Author
      - Title
      - Content
    example:
      Id: 23942bc0-0f89-11e6-9a21-000d3a207970
      LastChangeDateTimeUtc: 2016-05-01T00:00:00Z
      ValidFromDateTimeUtc: 2016-05-01T00:00:00Z
      ValidUntilDateTimeUtc: 2016-05-30T00:00:00Z
      Area: Development
      Author: Luchs
      Title: Announcements ready for testing
      Content: The announcements endpoint is now available for developers to test. Thank you for any feedback! :)
